# Generated by Django 4.0.2 on 2022-02-22 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_note_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='completed',
        ),
    ]
